name=ProtonSumo
version=1.0.0
author=Studentska organizacija Proton Elektrotehničkog fakulteta
maintainer=Studentska organizacija Proton Elektrotehničkog fakulteta
sentence=Arduino library for Robo Sumo autonomous robots
paragraph=Library for controlling sumo robots with IR tactic selection, ultrasonic sensing, and edge detection using dual IR sensors.
category=Robotics
url=
architectures=*